openapi: 3.1.0
info:
  title: Sample
  version: 0.0.1
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        country:
          $ref: '#/components/schemas/Country'
    Country:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
